# This CI/CD workflow does the following:
# - builds the project
# - deploys to stage pr-{github.event.pull_request.number}
# - runs unit and integration tests on this stage
# - auto-merges PRs from dependabot that passes the deployment job

name: Deploy and test pull requests

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "docs/**"

jobs:
  deploy:
    uses: hub335/sof-workflows/.github/workflows/sst-deploy.yml@master
    with:
      # A unique stage name for test deployment that includes the pull request number
      stage: ${{ format('pr-{0}', github.event.pull_request.number) }}
      environment: test
    secrets: inherit

  # automatically merge dependabot PRs that passes the build/test/deployment checks
  dependabot:
    runs-on: ubuntu-latest

    # only run this job for dependabot PRs
    if: ${{ github.actor == 'dependabot[bot]' }}

    # only run if the required checks pass
    needs: [deploy]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Auto-merge Dependabot PRs
        # find the PR number
        run: "gh pr merge --auto --squash ${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
